services:
  gpu-jupyter:
    container_name: gpu-jupyter
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
              # Uncomment to select a single GPU instead of all of them
              # device_ids: ["0"]
        # Uncomment to set hardware limits: max. 48GB RAM, max. 31 CPUs
        # limits:
        #   cpus: "15.0"
        #   memory: 48g
    ports:
      - 8848:8888
    volumes:
      - ./data:/home/jovyan/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    env_file:
      - path: token.env
        required: false
    # enable sudo permissions
    user:
      "root"
    restart: unless-stopped
