# Install PyTorch
RUN bash -c 'case "${PYTORCH_VERSION}-${CUDA}" in \
    "1.9.1-11.1") \
      pip install --no-cache-dir torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.9.1-10.2") \
      pip install --no-cache-dir torch==1.9.1 torchvision==0.10.1 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.9.1-") \
      pip3 install --no-cache-dir torch==1.9.1+cpu torchvision==0.10.1+cpu torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.9.0-11.1") \
      pip install --no-cache-dir torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.9.0-10.2") \
      pip install --no-cache-dir torch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.9.0-") \
      pip3 install --no-cache-dir torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.8.0-11.1") \
      pip install --no-cache-dir torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.8.0-10.2") \
      pip install --no-cache-dir torch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 ;; \
    "1.8.0-") \
      pip install --no-cache-dir torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.1-11.0") \
      pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.1-10.2") \
      pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 ;; \
    "1.7.1-10.1") \
      pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.1-9.2") \
      pip install torch==1.7.1+cu92 torchvision==0.8.2+cu92 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.1-") \
      pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.0-11.0")\
    pip install torch==1.7.0+cu110 torchvision==0.8.0+cu110 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.0-10.2")\
    pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 ;; \
    "1.7.0-10.1")\
    pip install torch==1.7.0+cu101 torchvision==0.8.0+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.0-9.2")\
    pip install torch==1.7.0+cu92 torchvision==0.8.0+cu92 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.7.0-")\
    pip install torch==1.7.0+cpu torchvision==0.8.0+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.6.0-10.2")\
    pip install torch==1.6.0 torchvision==0.7.0 ;; \
    "1.6.0-10.1")\
    pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.6.0-9.2")\
    pip install torch==1.6.0+cu92 torchvision==0.7.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.6.0-")\
    pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.1-10.2")\
    pip install torch==1.5.1 torchvision==0.6.1 ;; \
    "1.5.1-10.1")\
    pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.1-9.2")\
    pip install torch==1.5.1+cu92 torchvision==0.6.1+cu92 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.1-")\
    pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.0-10.2")\
    pip install torch==1.5.0 torchvision==0.6.0 ;; \
    "1.5.0-10.1")\
    pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.0-9.2")\
    pip install torch==1.5.0+cu92 torchvision==0.6.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html ;; \
    "1.5.0-")\
    pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html ;; \
    esac'
